let listanum = document.querySelectorAll('div.num')
let um = document.querySelector('div#um')
let dois = document.querySelector('div#dois')
let tres = document.querySelector('div#tres')
let quatro = document.querySelector('div#quatro')
let cinco = document.querySelector('div#cinco')
let listastr = document.querySelectorAll('div.str')
let oi = document.querySelector('div#oi')
let tchau = document.querySelector('div#tchau')
console.log(listanum)
console.log(um)
console.log(listastr)
console.log(oi)